steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/royal-lips:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/royal-lips:latest'
      - '.'
    timeout: 1200s

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/royal-lips:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/royal-lips:latest'

  # Update Database Schema
  - name: 'gcr.io/$PROJECT_ID/royal-lips:$COMMIT_SHA'
    entrypoint: 'npx'
    args: ['prisma', 'db', 'push', '--accept-data-loss']
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'royal-lips'
      - '--image'
      - 'gcr.io/$PROJECT_ID/royal-lips:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'


images:
  - 'gcr.io/$PROJECT_ID/royal-lips:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/royal-lips:latest'

timeout: 1800s

options:
  machineType: 'E2_HIGHCPU_8'
